"""Memory Provider ABC — from Hermes-Agent's pluggable memory design."""
from abc import ABC, abstractmethod
from typing import Any
class MemoryProvider(ABC):
    @abstractmethod
    def store(self, key: str, value: str, metadata: dict | None = None) -> str: ...
    @abstractmethod
    def recall(self, query: str, limit: int = 5) -> list[dict]: ...
    @abstractmethod
    def search(self, query: str, limit: int = 10) -> list[dict]: ...
    @abstractmethod
    def sync_turn(self, turn_messages: list[dict]) -> None: ...
    @abstractmethod
    def shutdown(self) -> None: ...
